spring.application.name=jobapplication

spring.datasource.url=jdbc:postgresql://localhost:5432/jobapplication
spring.datasource.username=postgres
spring.datasource.password=kishore

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
